version: '3.9'
services:
  database:
    image: postgres:14.5-alpine
    ports:
      - "5432:5432"
    restart: always
    deploy:
      resources:
        limits:
          memory: 2000M
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - PGPASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB_NAME}
  api:
    build: .
    depends_on:
      - database
    ports:
      - "3333:3333"
    restart: always
    volumes:
      - .:/usr/src/app
    deploy:
      resources:
        limits:
          memory: 2000M